footprint: [[-0.16, -0.18], [-0.16, 0.18], [0.16, 0.18], [0.16, -0.18]]
footprint_padding: 0.01

robot_base_frame: camera_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 3.0
raytrace_range: 3.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_rgbd:
    observation_sources: point_cloud_sensor
    point_cloud_sensor: {
        data_type: PointCloud2, 
        clearing: true, 
        marking: true, 
        topic: /rtabmap/cloud_obstacles, 
        min_obstacle_height: 0.0, 
        max_obstacle_height: 0.1}

inflation:
    inflation_radius: 0.1
