footprint: [[-0.16, -0.18], [-0.16, 0.18], [0.16, 0.18], [0.16, -0.18]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 3.0
raytrace_range: 3.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {
        data_type: LaserScan, 
        clearing: true, 
        marking: true, 
        topic: scan, 
        inf_is_valid: true}

obstacles_rgbd:
    observation_sources: scan
    scan: {
        data_type: LaserScan, 
        topic: /camera/scan,
        clearing: true, 
        marking: true}

inflation:
    inflation_radius: 0.1
